var addedService = [
//{
//	name: '數據恢復',
//	 nameEn: 'aqfhgj',
//	 desc: '數據恢復',
//	 price: 1500,
//	 unit:'/帳套',
//	 btnValue:'申請',
//	 imgSrc: '../images/value-added-icon.png',
//	 imgSrcSmall: '../images/value-added-icon-48.png',
//	 imgOutStyle:'background-position:0 0;',
//	 imgOutStyleSmall:'background-position:0 0;',
//	 buyLink: '',
//	 detailsLink: '',
//	 productId: 21,
//	 info: null //產品資訊，包括計算后的價格、到期時間等等
//},
{
	name: '套打設計',
	 nameEn: 'tdsj',
	 desc: '套打設計',
	 price: 200,
	 unit:'/張',
	 btnValue:'申請',
	 linkType:'',
	 imgSrc: '../images/value-added-icon.png',
	 imgSrcSmall: '../images/value-added-icon-48.png',
	 imgOutStyle:'background-position:-64px 0;',
	 imgOutStyleSmall:'background-position:-48px 0;',
	 buyLink: 'http://www.istheme.com/i/253',
	 detailsLink: 'http://www.istheme.com/i/253',
	 productId: 101807,
	 info: null //產品資訊，包括計算后的價格、到期時間等等
},{
	name: '產品培訓',
	 nameEn: 'cppx',
	 desc: '產品培訓',
	 price: 500,
	 unit:'/次起',
	 btnValue:'申請',
	 linkType:'',
	 imgSrc: '../images/value-added-icon.png',
	 imgSrcSmall: '../images/value-added-icon-48.png',
	 imgOutStyle:'background-position:-192px 0;',
	 imgOutStyleSmall:'background-position:-144px 0;',
	 buyLink: 'http://www.istheme.com/i/253',
	 detailsLink: 'http://www.istheme.com/i/253',
	 productId: 101807,
	 info: null //產品資訊，包括計算后的價格、到期時間等等
},{
	name: '專屬顧問服務',
	 nameEn: 'zsgwfw',
	 desc: '專屬顧問服務',
	 price: 200,
	 unit:'/月起',
	 btnValue:'申請',
	 linkType:'',
	 imgSrc: '../images/value-added-icon.png',
	 imgSrcSmall: '../images/value-added-icon-48.png',
	 imgOutStyle:'background-position:-256px 0;',
	 buyLink: 'http://www.istheme.com/i/253',
	 detailsLink: 'http://www.istheme.com/i/253', 
	 productId: 101807,
	 info: null //產品資訊，包括計算后的價格、到期時間等等
}
//,{
//	name: '初始化服務',
//	 nameEn: 'cshfw',
//	 desc: '初始化服務',
//	 price: 500,
//	 unit:'元/賬套起',
//	 btnValue:'免費',
//	 linkType:'setting-advancedSetting-right',
//	 imgSrc: '../images/value-added-icon.png',
//	 imgSrcSmall: '../images/value-added-icon-48.png',
//	 imgOutStyle:'background-position:-320px 0;',
//	 buyLink: '',
//	 detailsLink: '',
//	 productId: 101807,
//	 info: null //產品資訊，包括計算后的價格、到期時間等等
//}
];